aldia/urls.py
#coding=UTF-8
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.auth.views import login, logout
from core.views import inicio, contact, buscador, suscripcion, gracias
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', inicio),
    (r'^contacto/$', contact),
    (r'^demo/', include('jarrett.urls.resumenes')),
    (r'^resumenes/', include('coltrane.urls.resumenes')),
    (r'^usuario/login/', login),
    (r'^usuario/logout/', logout, {'next_page': '/' }),
    (r'^buscar/$', buscador),
    (r'^suscripcion/$', suscripcion),
    (r'^gracias/$', gracias),
    #(r'^', include('marketing.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
        }),
)

urlpatterns += patterns('',
    #url(r'^aviso-legal/$', 'flatpage', {'url': '/aviso-legal/'}, name='legal'),
    #url(r'^privacidad/$', 'flatpage', {'url': '/privacidad/'}, name='privacidad'),
    ('^privacidad/', include('django.contrib.flatpages.urls')),
    ('^devolucion/', include('django.contrib.flatpages.urls')),
)

temp/urls.py
#coding=UTF-8
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.auth.views import login, logout
from core.views import inicio, contact, buscador, suscripcion, gracias
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', inicio),
    (r'^contacto/$', contact),
    (r'^demo/', include('jarrett.urls.resumenes')),
    (r'^resumenes/', include('coltrane.urls.resumenes')),
    (r'^usuario/login/', login),
    (r'^usuario/logout/', logout, {'next_page': '/' }),
    (r'^buscar/$', buscador),
    (r'^suscripcion/$', suscripcion),
    (r'^gracias/$', gracias),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
    #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
    #    'document_root': settings.MEDIA_ROOT,
    #    }),
)

urlpatterns += patterns('',
    #url(r'^aviso-legal/$', 'flatpage', {'url': '/aviso-legal/'}, name='legal'),
    #url(r'^privacidad/$', 'flatpage', {'url': '/privacidad/'}, name='privacidad'),
    ('^privacidad/', include('django.contrib.flatpages.urls')),
    ('^devolucion/', include('django.contrib.flatpages.urls')),
)

core/forms.py
#coding=UTF-8

from django import forms
import re

class SearchFormKeyword(forms.Form):
    RADIO_PERIODO_CHOICES = (
        ('DI', 'Diario'),
        ('SE', 'Semanal'),
        ('ME', 'Mensual'),
        ('AN', 'Anual'),
    )
    keywords = forms.CharField(max_length=40, required=False, widget=forms.TextInput(attrs={'size':'14'}))
    fecha_periodo = forms.ChoiceField(label='Periodo de Busqueda', choices=RADIO_PERIODO_CHOICES)
    def clean_keywords(self):
        keywords = self.cleaned_data['keywords']
        if not re.search(r'^\w+$', keywords):
            raise forms.ValidationError(u'Las palabras solo pueden tener caracteres alfanumericos y guion bajo.')

class ContactForm(forms.Form):
    TIPO_CHOICES = (
        ('', '--- Elija tipo de asunto ---'),
        ('SUGERENCIA', 'Sugerencias'),
        ('INFORMACIÓN', 'Información'),
        ('PROBLEMAS', 'Problemas'),
        ('OTROS', 'Otros'),
    )
    tipo = forms.ChoiceField(label='', choices=TIPO_CHOICES)    
    asunto = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'size':'30'}))
    email = forms.EmailField(required=False, max_length=30, widget=forms.TextInput(attrs={'size':'25'}))
    mensaje = forms.CharField(widget=forms.Textarea(attrs={'cols':'35','rows':'10' }), max_length=200)

class RegistroForm(forms.Form):
    email = forms.EmailField(required=False, max_length=30, widget=forms.TextInput(attrs={'size':'25'}))
    mensaje = forms.CharField(widget=forms.Textarea(attrs={'cols':'35','rows':'10' }), max_length=200)

templates/base_resumen.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
                "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>La Prensa de Hoy - Toda la actualidad económica a primera hora de la mañana | {% block head_title %}{% endblock %}</title>
    {% block meta_name_description %}{% endblock %}

	<meta name="keywords" content="prensa, resumen, económica, economía, actualidad" />
	<meta http-equiv="content-language" content="es-ES">
	<meta name="language" content="spanish">
	<meta name="La Prensa de Hoy" content="" />
	<link href="/static/css/resumen.css" rel="stylesheet" type="text/css" media="screen" />

    <script type='text/javascript' src='/static/js/jquery-1.3.2.min.js'></script>
    <script type='text/javascript' src='/static/js/lavalamp.min.js'></script>
    <script type='text/javascript' src='/static/js/easing.js'></script>
    <script type="text/javascript">
    /* <![CDATA[ */
    $(function(){$(".lavaLamp").lavaLamp({ fx: "backout", speed: 700 })});
    /* ]]> */
    </script>

	{% block estilo %}{% endblock %}
	{% block js %}{% endblock %}

	<!--[if IE]>
	<style>
	legend {
	position: absolute;
	top: -.5em;
	left: .2em;
	padding-bottom: .1em;
	}
	
	fieldset {
	position: relative;
	margin-top: 1em;
	padding-top: .8em;
	padding-left: .4em;
	}
	fieldset input {
	left: .2em;
	}
	</style>
	<![endif]--> 
</head>

<body>
<div id="wrapper">

<!-- start header -->
    <div id="header">
    
    <h1><a href="/"></a></h1>
    <form action="/buscar/">
        <input type="text" id="id_keywords" name="keywords" value="Buscar resúmenes..." onfocus="if (value =='Buscar resúmenes...'){value =''}" onblur="if (value ==''){value='Buscar resúmenes...'}" />
        <input type="hidden" value="keywordsearch" name="tipobusqueda">
        <input type="submit" value=" " id="searchsubmit"/>
    </form>
   	<div id="usuarios">
    	<ul>
       		{% if user.is_authenticated %}
       		    <li class="printer"><a href="javascript:window.print()">Imprimir</a><span> / </span></li>
       			<li><a href="/usuario/logout/">Salir</a></li>
       		{% else %}
       		    <li class="printer"><a href="javascript:window.print()">Imprimir</a><span> / </span></li>
       			<li><a href="/resumenes/">Acceso</a><span> / </span></li>
       			<li><a href="/register/">Registrarse</a></li>
       		{% endif %}
    	</ul>
   	</div>
    
    </div>
{% block navi %}
{% endblock %}

<!-- end header -->

	<!-- start page -->
	{% block contenido %}
	{% endblock %}
	{% comment %} 
	<div id="page">
		<!-- start content -->
		{% block content %}
		{% endblock %}
		<!-- end content -->
		
		<!-- start sidebars -->
		{% block sidebar %}
		{% endblock %}
		<!-- fin div sidebars -->
		<div style="clear: both;">&nbsp;</div>
	</div>
	{% endcomment %}
	<!-- end page -->

<!-- fin div wrapper -->

</div>
</body>
</html>

templates/base_resumen_detail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
                "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>La Prensa de Hoy - Toda la actualidad económica a primera hora de la mañana | {% block head_title %}{% endblock %}</title>
    {% block meta_name_description %}{% endblock %}

	<meta name="keywords" content="prensa, resumen, económica, economía, actualidad" />
	<meta http-equiv="content-language" content="es-ES">
	<meta name="language" content="spanish">
	<meta name="La Prensa de Hoy" content="" />
	<link rel="stylesheet" href="/static/css/print.css" type="text/css" media="print" />
	<link href="/static/css/resumen_detail.css" rel="stylesheet" type="text/css" media="screen" />
	<link href='http://fonts.googleapis.com/css?family=Ubuntu:light' rel='stylesheet' type='text/css'>

    <!--<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>-->
    <script type='text/javascript' src='http://code.jquery.com/jquery-1.7.2.min.js'></script>
    <script type='text/javascript' src='/static/js/jquery.easing.1.3.js'></script>
    <script type='text/javascript' src='/static/js/jquery.lavalamp.1.4.min.js'></script>
    <!--<script type='text/javascript' src='/static/js/jquery.easing.js'></script>-->
    <!--<script type='text/javascript' src='/static/js/jquery.easing.compatibility.js'></script>-->
    <script type="text/javascript" src="/static/js/jquery.ui.totop.min.js"></script>
    <script type="text/javascript">
    $(function(){$('ul#menulava').lavaLamp({ speed: 700 })});
    </script>
    <script type="text/javascript">
        $(document).ready(function() {
            /*
            var defaults = {
                containerID: 'moccaUItoTop', // fading element id
                containerHoverClass: 'moccaUIhover', // fading element hover class
                scrollSpeed: 1200,
                easingType: 'linear' 
            };
            */
            
            $().UItoTop({ easingType: 'easeOutQuart' });
            
        });
    </script>
    <script type="text/javascript">
    /*$(document).ready(function(){
        $(".trigger").bind(" click touch tap ", function(){
            $("#rightColumn").toggle("fast");
            $(this).toggleClass("display");
            return false;
        });
        $(".indice").bind("click touch tap", function(){
            $("#rightColumn").toggle("fast");
            return;
        });
    });*/
/*
        $(document).ready(function() {
            $('#click').click(function(){
                $("#rightColumn").animate({width:'toggle'},500);
            });
        });
*/
    </script>
	{% block estilo %}{% endblock %}
	{% block js %}{% endblock %}

	<!--[if IE]>
	<style>
	legend {
	position: absolute;
	top: -.5em;
	left: .2em;
	padding-bottom: .1em;
	}
	
	fieldset {
	position: relative;
	margin-top: 1em;
	padding-top: .8em;
	padding-left: .4em;
	}
	fieldset input {
	left: .2em;
	}
	</style>
	<![endif]--> 
</head>

<body>
<div id="wrapper">

<!-- start header -->
    <div id="header">
    
    <h1><a href="/"></a></h1>
    <form action="/buscar/">
        <input type="text" id="id_keywords" name="keywords" value="Buscar resúmenes..." onfocus="if (value =='Buscar resúmenes...'){value =''}" onblur="if (value ==''){value='Buscar resúmenes...'}" />
        <input type="hidden" value="keywordsearch" name="tipobusqueda">
        <input type="submit" value=" " id="searchsubmit"/>
    </form>
   	<div id="usuarios">
    	<ul>
       		{% if user.is_authenticated %}
                {% comment %}
                <li><a href="/ezpdf_sample/" class="gray-btn">PDF</a><span> /&nbsp;</span></li>
                {% endcomment %}
       		    <li class="printer"><a href="javascript:window.print()">Imprimir</a><span> /&nbsp;</span></li>
       			<li><a href="/usuario/logout/">Salir</a></li>
       		{% else %}
                {% comment %}
                <li><a href="/ezpdf_sample/" class="gray-btn">PDF</a></li>
                {% endcomment %}
       		    <li class="printer"><a href="javascript:window.print()">Imprimir</a><span> /&nbsp;</span></li>
       			<li><a href="/resumenes/">Acceso</a><span> /&nbsp;</span></li>
       			<li><a href="/register/">Registrarse</a></li>
       		{% endif %}
    	</ul>
   	</div>
    
    </div>
{% block navi %}
{% endblock %}

<!-- end header -->

	<!-- start page -->
	{% block contenido %}
	{% endblock %}
	{% comment %} 
	<div id="page">
		<!-- start content -->
		{% block content %}
		{% endblock %}
		<!-- end content -->
		
		<!-- start sidebars -->
		{% block sidebar %}
		{% endblock %}
		<!-- fin div sidebars -->
		<div style="clear: both;">&nbsp;</div>
	</div>
	{% endcomment %}
	<!-- end page -->
<div id=footer align="center">
<script language="Javascript" type="text/javascript" src="http://widgets.elpais.com/liga/wlaunch.html?c=gris&w=400">  
</script> 

</div>
<!-- fin div wrapper -->

</div>
</div>

</body>
</html>

templates/busqueda.html
{% extends "base_busqueda.html" %}
{% block head_title %}{{ block.super }} Búsqueda{% endblock %}
{% block meta_name_description %}
<meta name="description" content="Búsqueda de conciertos de música clásica.Buscar por intérpretes, compositores, época, genero, precio, ciclos de música clásica y fechas.">
{% endblock %}

{% block estilo %}
{% endblock %}

{% block js %}
    <script type="text/javascript" src="/static/js/search.js"></script>
{% endblock %}

{% block page_title %}Buscador La Prensa de Hoy{% endblock %}
{% block navi %}
<div id="navi">
    <ul class="lavaLamp">
        <li><a title="Inicio La Prensa de Hoy" href="/">Inicio</a></li>
        <li class="current"><a title="buscar" href="/buscar/">Búsqueda</a></li>
        <li><a title="noticias" href="/resumenes/">Resúmenes</a></li>
        <li><a title="demo" href="/demo/">Demo</a></li>
        <li><a title="contacte con La Prensa de Hoy" href="/contacto/">Contacto</a></li>
    </ul>
</div>  
{% endblock %}


{% block contenido %}
<div id="container-top"></div>
<div id="container">
<div id="content">
    <div id="posts"><!-- posts-start -->
        <div class="post text">
            <div class="postinfo">
                <div class="labels">
                        <div class="date">
                            <span class="smaller">{{ ahora|date:"M" }}</span><br><span>{{ ahora|date:"j" }}<span><br></span></span>
                        </div>
                </div>
        
                    
            </div><!-- .postinfo -->
            <span class="posttitle"><h2>Búsqueda en el Archivo de La Prensa de Hoy</h2></span>
            <div class="regular_post_body">
                <p>La función de búsqueda permite buscar palabras clave sobre el Archivo de La Prensa de Hoy.</p>
                <p>Funcionalidad:</p>
                <ul><li>Búsqueda en un periodo de tiempo.</li>
                <li>Periodos de tiempo: hoy, mensual, trimestral y anual.</li>
                <li>Acceso directo al documento original.</li>
                </ul>
            </div>
            <a rel="nofollow" href="#" class="vialink">Comentarios</a>
            <br class="clear">
            <div id="search-resultados">
                {{ lista_resultados }}
            </div>
        </div><!-- .post -->
    </div><!-- #posts --><!-- posts-end -->
    
    <div id="sidebar">

        <br>
        <h2>Buscar</h2>
        <br>
    <div id="buscador">
        {% block form1 %}
        <form id="search-form" method="get" action=".">
            <table><tbody>
            <tr><td>
            <input type="text" id="id_keywords" title='Para búsquedas exactas introduzca las palabras entre comillas. Ejemplo: "palabra1 palabra2" ' name="keywords" maxlength="40" />
            <input type="hidden" name="tipobusqueda" value="keywordsearch" /></td>
            <td>
            <input type="submit" value=" " id="searchsubmit" name="submit" /></td>
            </tr>
            <tr><td>
            <select name="fecha_periodo" id="fecha_periodo">
                <option value='ME' selected="selected">Mensual</option>
                <option value='TR'>Trimestral</option>
                <option value='SE'>Semestral</option>
                <option value='AN'>Anual</option>
                <option value='TO'>Todo</option>
            </select></td></tr>
            <tr></tr>
            </tbody></table>
            </table>
            <input type="reset" id="borrador" value="Borrar">
        </form>
        {% endblock %}
    </div>
    <div id="errores">
        {{ form_key.keywords.errors }}
    </div>
        
        <br>
        
        <h2>Info</h2>
        <span id="about-text">Introduzca las palabras clave en el campo superior y pulse Intro o cliquée la lupa.
<br><br>
Puede limpiar el campo de búsqueda pulsando en Borrar.


        <br class="clear">
        
        <br>

        <ul class="links">
            
            <li><span><a href="/resumenes/">Resúmenes</a></span></li>
            
            <li><span><a href="/contacto/">Contacto</a></span></li>
        </ul>

                <div id="buttons">
                    {% comment %}
                    <div class="row">
                        <div class="button" id="button-archive"><a href="/resumenes/">Archivo</a></div>
                        <div class="button" id="button-mobile"><a rel="nofollow" href="#">Móvil</a></div>
                    </div>
                    <div class="clear"></div>
                    <div class="row">
                        <div class="button" id="button-rss"><a href="http://www.twitter.com/prensadehoy">Twitter</a></div>
                        <div class="button" id="button-random"><a rel="nofollow" href="#">Estadísticas</a></div>
                    </div>
                    {% endcomment %}
                    <div class="clear"></div>
                </div>

        </div>
        </div><!-- #content -->
    </div><!-- #container -->
    <div id="container-bottom">
        <div id='parriba'>&nbsp;</div>
    <script type="text/javascript">
    $(window).scroll(function() {
        if ($(this).scrollTop()) {
            $('#parriba').fadeIn();
        } else {
            $('#parriba').fadeOut();
        }
    });
    $("#parriba").click(function() {
        $("html, body").animate({scrollTop: 0}, 1000);
    });
    </script>
    </div>
    <div class="clear"></div>
    <br>

{% endblock contenido %}

templates/contacto.html
{% extends "base.html" %}
{% block head_title %}{{ block.super }} Contacto{% endblock %}
{% block meta_name_description %}
<meta name="description" content="Contacto con La Prensa de Hoy. Sugerencias, Información.">
{% endblock %}


{% block navi %}
<div id="navi">
    <ul class="lavaLamp">
		<li><a title="Inicio La Prensa de Hoy" href="/">Inicio</a></li>
		<li><a title="buscar" href="/buscar/">Búsqueda</a></li>
		<li><a title="noticias" href="/resumenes/">Resúmenes</a></li>
		<li><a title="demo" href="/demo/">Demo</a></li>
		<li class="current"><a title="contacte con La Prensa de Hoy" href="/contacto/">Contacto</a></li>
	</ul>
</div>	
{% endblock %}

{% block contenido %}
<div class="span-13 prepend-1 colborder" id="content-main">
<div class="contactoouter">
	<div class="contactoiner">

    <fieldset>
        <div class="contactotitle">Contáctenos</div>
        {% if form.errors %}
            <p style="color: red;">
            Por favor, corrija el error{{ form.errors|pluralize }} de abajo.
            </p>
        {% endif %}
        <form id="contactoform" action="" method="post">
            <table>
                {{ form.as_table }}
            </table>
            <p id="contacto_button">
            <input type="submit" value="Enviar">
            <input type="reset" value="Borrar">
            </p>
        </form>
    </fieldset>
    </div>
</div>
</div>
{% endblock contenido %}
   

templates/resultados.html
{% extends "base_busqueda.html" %}
{% block head_title %}{{ block.super }} Búsqueda{% endblock %}
{% block meta_name_description %}
<meta name="description" content="Búsqueda de conciertos de música clásica.Buscar por intérpretes, compositores, época, genero, precio, ciclos de música clásica y fechas.">
{% endblock %}

{% block estilo %}
<!-- <link rel="stylesheet" type="text/css" href="/static/css/jquery.autocomplete.css" /> --> 
<!-- <link rel="stylesheet" type="text/css" href="/static/css/thickbox.css" /> -->
{% endblock %}

{% block js %}
    <!-- <script type="text/javascript" src="/static/js/autocomplete/jquery.js"></script> -->
    <!-- <script type="text/javascript" src="/static/js/autocomplete/jquery.bgiframe.min.js"></script> -->
    <!-- <script type="text/javascript" src="/static/js/autocomplete/jquery.ajaxQueue.js"></script> -->
    <!-- <script type="text/javascript" src="/static/js/autocomplete/thickbox-compressed.js"></script> -->
    <script type="text/javascript" src="/static/js/search.js"></script>
    {% comment %}
    <script type="text/javascript" src="/static/js/autocomplete/jquery.autocomplete.js"></script>
    <script type="text/javascript" src="/static/js/autocomplete/localdata.js"></script>

    <script type="text/javascript">
    $().ready(function() {

    function log(event, data, formatted) {
        $("<li>").html( !data ? "No match!" : "Selected: " + formatted).appendTo("#result");
    }
    
    function formatItem(row) {
        return row[0] + " (<strong>id: " + row[1] + "</strong>)";
    }
    function formatResult(row) {
        return row[0].replace(/(<.+?>)/gi, '');
    }
    
    $("#suggest1").focus().autocomplete(cities);
    $("#id_keywords").autocomplete(cities, {
        multiple: true,
        matchContains: true,
        multipleSeparator: " ",
        autoFill: true
    });
    
    $(":text, textarea").result(log).next().click(function() {
        $(this).prev().search();
    });
    $("#scrollChange").click(changeScrollHeight);
    
    $("#clear").click(function() {
        $(":input").unautocomplete();
    });
});

    </script>
    {% endcomment %}

{% endblock %}

{% block page_title %}Buscador La Prensa de Hoy{% endblock %}
{% block navi %}
<div id="navi">
    <ul class="lavaLamp">
        <li><a title="Inicio La Prensa de Hoy" href="/">Inicio</a></li>
        <li class="current"><a title="buscar" href="/buscar/">Búsqueda</a></li>
        <li><a title="noticias" href="/resumenes/">Resúmenes</a></li>
        <li><a title="demo" href="/demo/">Demo</a></li>
        <li><a title="contacte con La Prensa de Hoy" href="/contacto/">Contacto</a></li>
    </ul>
</div>  
{% endblock %}


{% block contenido %}
<div id="container-top"></div>
<div id="container">
<div id="content">
    <div id="posts"><!-- posts-start -->
    {% for lista in lista_resultados %}
    <div class="post text">
        <div class="postinfo">
           {% if not errors and found %}
           <div class="labels">
                    <div class="date">
                        <span class="smaller">{{ lista.0|date:"M" }}</span><br><span>{{ lista.0|date:"j" }}<span><br></span></span>
                    </div>
            </div>
            {% endif %}
        
                    
        </div><!-- .postinfo -->
        {% if errors %}
            <ul><li id="error-busqueda">{{ lista.0.0 }}</li></ul>
        {% endif %}
        {% if not errors and not found %}
            {% for parrafo in lista.2 %}
            <ul><li id="nofound-busqueda">{{ parrafo }}</li></ul>
            {% endfor %}
        {% endif %}
        {% if not errors and found %}
            <span class="posttitle"><h2><a href="{{ lista.1 }}"><img src="/static/images/logo-lpdh-resultados.png" alt="logo" />&nbsp;&nbsp;{{ lista.0|date:"j \d\e F, Y" }}</a></h2></span>
            <div class="regular_post_body">
                {% for parrafo in lista.2 %}
                    <ul>
                    <li>{{ parrafo|safe }}</li>
                    </ul>
                {% endfor %}
            </div>
            <a rel="nofollow" href="#" class="vialink">{{ lista.3 }} Resultados</a>
        {% endif %}
        <br>
        {% if not errors and found %}
            <ul class="tags" style="float:right;">
            <li><a href="{{ lista.1 }}">&laquo;&laquo;&nbsp;&nbsp;Leer resumen&nbsp;&nbsp;&raquo;&raquo;</a></li>
            </ul>
        {% endif %}
        <br class="clear">
    </div>
    {% endfor %}
    </div><!-- #posts --><!-- posts-end -->

    <div id="sidebar">

        <br>
        <h2>Buscar</h2>
        <br>
    <div id="buscador">
        {% block form1 %}
        <form id="search-form" method="get" action=".">
            <table><tbody>
            <tr><td>
            <input type="text" id="id_keywords" name="keywords" maxlength="40" />
            <input type="hidden" name="tipobusqueda" value="keywordsearch" />
            <input type="submit" value=" " id="searchsubmit"/></td></tr>
            <tr><td>
            <select name="fecha_periodo" id="id_fecha_periodo">
                <option value="DI">Diario</option>
                <option value="SE">Semanal</option>
                <option value="ME">Mensual</option>
                <option value="AN">Anual</option>
            </select></td></tr>
            </tbody></table>
            </table>
            <input type="reset" id="borrador" value="Borrar">
        </form>
        {% endblock %}
    </div>
    <div id="errores">
        {{ form_key.keywords.errors }}
    </div>
        
        <br>
        
        <h2>Info</h2>
        <span id="about-text">Introduzca las palabras clave en el campo superior y pulse Intro o cliquée la lupa.
<br><br>
Puede limpiar el campo de búsqueda pulsando en Borrar.


        <br class="clear">
        
        <br>



        <ul class="links">
            
            <li><span><a href="/resumenes/">Resúmenes</a></span></li>
            
            
            
            <li><span><a href="/contacto/">Contacto</a></span></li>
        </ul>

     
                
                <div id="buttons">
                {% comment %}
                    <div class="row">
                        <div class="button" id="button-archive"><a href="/resumenes/">Archivo</a></div>
                        <div class="button" id="button-mobile"><a rel="nofollow" href="#">Móvil</a></div>
                    </div>
                    <div class="clear"></div>
                    <div class="row">
                        <div class="button" id="button-rss"><a href="http://www.twitter.com/prensadehoy">Twitter</a></div>
                        <div class="button" id="button-random"><a rel="nofollow" href="#">Estadísticas</a></div>
                    </div>
                {% endcomment %}
                    <div class="clear"></div>
                </div>

        </div>
        </div><!-- #content -->
    </div><!-- #container -->
    <div id="container-bottom">
        
            <div id="load-more-posts"><span class="spinner"></span><p>Load more posts…</p></div>        
            <div id="hidden_navinfo"><!-- this is necessary for ajax pagination --><span class="startpage">1</span><span class="totalpages">3</span></div>
             <div id="classic-pagination">
                
                 <a href="http://ppa.webupd8.org/page/2" id="next-page">Next page</a>
            </div><!-- #classic-pagination -->
        
        <a rel="nofollow" href="http://www.pixelunion.net/" id="pixelunion-link">To Tumblr, Love PixelUnion</a>
    </div>

    
    
    <br>

{% endblock contenido %}